### PR TITLE
srun argument depending on slurm version

### PR DESCRIPTION
**Pull request by pkopta**
Solves problems with `srun`'s `--cpu-bind`/`--cpu_bind` argument between Slurm versions.

### CODE REVIEW

**Comment by LourensVeen** [comment]
Looks great!

**Comment by LourensVeen** [comment]
Okay, I was a little too quick there. I tested it, and it's not quite working because there's another instance of `--cpu-bind` in `launcher/launcher.py`. It looks like it works if I apply the same fix there.

**Comment by pkopta** [comment]
Mea culpa - I somehow missed that place

**Comment by LourensVeen** [comment]
Perfect!

**Pull request merged**
